Repository lion-packages/command, pull requests merged in 2025-04, with the labels that each got.

#19 Integrate PHPLint
  .github/workflows/php.yml
  .gitignore
  composer.json
Labels: continuous integration

#20 The infection library is installed
  .env.actions
  .env.example
  .github/workflows/php.yml
  .gitignore
  composer.json
  infection.json
  phpunit.xml
  src/LionCommand/Kernel.php
  tests/KernelTest.php
  tests/Providers/KernelProviderTrait.php
  tests/bootstrap.php
Labels: dependencies, tests

#21 Infection is integrated
  .github/workflows/php.yml
Labels: continuous integration

#22 Update README.md
  .github/README.md
Labels: documentation

#26 Added StyleCI configuration
  .styleci.yml
  src/LionCommand/Command.php
  src/LionCommand/Kernel.php
  tests/CommandTest.php
  tests/KernelTest.php
  tests/Providers/KernelProviderTrait.php
  tests/bootstrap.php
Labels: continuous integration

#34 Update dependabot.yml
  .github/dependabot.yml
Labels: continuous integration

#36 Define the execution time for Github Actions
  .github/workflows/php.yml
Labels: continuous integration
